export const categories = [
  {
    slug: "chopping-boards",
    name: "Chopping Boards",
    description: "Heavy-duty organic-edge cutting boards, end-grain blocks, and utility prep boards crafted for years of daily kitchen use.",
    count: 5,
    image: "/images/products/acacia-cutting-board.jpg",
  },
  {
    slug: "serving-trays",
    name: "Serving Platters",
    description: "Bespoke Acacia platters, circular serving trays, cake stands, and snack bowls designed to elevate dining setups.",
    count: 4,
    image: "/images/products/wall-shelf-1.jpg",
  },
  {
    slug: "kitchen-organizers",
    name: "Kitchen Organizers",
    description: "Partitioned wooden cutlery holders, roti boxes, napkin stands, and countertop storage units shaped to organize your culinary hub.",
    count: 2,
    image: "/images/products/chopping-board-v2.jpg",
  },
  {
    slug: "tableware-living",
    name: "Tableware & Sofa Accents",
    description: "Acacia tea trivets, coaster sets, and flexible wrap-around sofa arm trays bringing natural wood warmth to living spaces.",
    count: 2,
    image: "/images/products/chopping-board-h1.jpg",
  },
  {
    slug: "wall-decor",
    name: "Wall Decor",
    description: "Handcrafted wooden wall shelves, key holders, photo frames, and temple pieces to bring warmth and artisan character to your walls.",
    count: 4,
    image: "/images/products/wall-shelf-1.jpg",
  },
];

export const products = [
  // ── Chopping Boards ──────────────────────────────────────────
  {
    id: "helsinki-acacia-board",
    name: "Acacia Classic Paddle Chopping Board",
    slug: "helsinki-acacia-board",
    category: "chopping-boards",
    categoryName: "Chopping Boards",
    price: 999,
    originalPrice: 1499,
    images: [
      "/images/products/acacia-cutting-board.jpg",
      "/images/products/chopping-board-v1.jpg",
    ],
    description:
      "A highly durable paddle chopping board crafted from single-block Acacia wood with a carved top handle for easy grip and hanging display.",
    features: [
      "Crafted from premium, sustainably sourced single-block Acacia wood",
      "Finished with 100% food-safe organic oil and natural beeswax",
      "Features an elegant cut-out handle for easy carrying and hanging storage",
      "Gentle on high-end kitchen knives, preventing rapid dulling of blades",
    ],
    specs: [
      { key: "Dimensions", value: "Length 42cm, Width 23cm" },
      { key: "Wood Type", value: "Acacia Wood" },
      { key: "Weight", value: "1.2 kg" },
    ],
    stock: 25,
    colors: ["Natural Acacia"],
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    id: "mika-acacia-board",
    name: "Horizontal Acacia Cutting Board",
    slug: "mika-acacia-board",
    category: "chopping-boards",
    categoryName: "Chopping Boards",
    price: 699,
    originalPrice: 999,
    images: [
      "/images/products/chopping-board-h1.jpg",
      "/images/products/chopping-board-flat.jpg",
    ],
    description:
      "A sleek horizontal cutting board crafted from golden Acacia wood, featuring a side cut-out handle for effortless kitchen prep.",
    features: [
      "Single-block solid Acacia timber construction",
      "Food-grade natural beeswax and linseed oil rub",
      "Side cut-out handle for comfortable grip and hanging storage",
      "Protects sharp knife edges during daily cutting",
    ],
    specs: [
      { key: "Dimensions", value: "Length 42cm, Width 21cm" },
      { key: "Wood Type", value: "Acacia Wood" },
      { key: "Weight", value: "0.9 kg" },
    ],
    stock: 50,
    colors: ["Natural Golden"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "oslo-acacia-prep-board",
    name: "Oslo Heavy-Duty Acacia Prep Board",
    slug: "oslo-acacia-prep-board",
    category: "chopping-boards",
    categoryName: "Chopping Boards",
    price: 1199,
    originalPrice: 1799,
    images: [
      "/images/products/chopping-board-v2.jpg",
      "/images/products/chopping-board-v1.jpg",
    ],
    description:
      "A thick, heavy-duty block-style cutting board engineered for serious kitchen prep with side finger grips.",
    features: [
      "1.5-inch thick block construction for maximum stability",
      "Carved side finger grooves for ergonomic lifting and cleaning",
      "Heavy enough to stay firmly in place while slicing large vegetables",
      "Pre-treated with heavy food-grade mineral oil baths",
    ],
    specs: [
      { key: "Dimensions", value: '16" L x 12" W x 1.5" H' },
      { key: "Wood Type", value: "End-grain style Acacia Wood" },
      { key: "Weight", value: "2.4 kg" },
    ],
    stock: 12,
    colors: ["Deep Walnut-Honey"],
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    id: "artisanal-flat-board",
    name: "Artisanal Organic Flat Cutting Board",
    slug: "artisanal-flat-board",
    category: "chopping-boards",
    categoryName: "Chopping Boards",
    price: 849,
    originalPrice: 1199,
    images: [
      "/images/products/chopping-board-flat.jpg",
      "/images/products/chopping-board-h1.jpg",
    ],
    description:
      "A wide, low-profile cutting board hand-carved from solid Acacia wood with organic live-edge curves.",
    features: [
      "Smooth food-safe organic oil finish showcasing rich natural wood grains",
      "Wide surface area ideal for slicing bread, cheese, and vegetables",
      "Durable hardwood construction engineered to resist warping",
    ],
    specs: [
      { key: "Dimensions", value: "38cm L x 25cm W x 2cm H" },
      { key: "Wood Type", value: "Solid Acacia Wood" },
      { key: "Weight", value: "1.4 kg" },
    ],
    stock: 20,
    colors: ["Warm Acacia Honey"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "artisan-charcuterie-board",
    name: "Artisan Cheese & Charcuterie Board",
    slug: "artisan-charcuterie-board",
    category: "chopping-boards",
    categoryName: "Chopping Boards",
    price: 1499,
    originalPrice: 1999,
    images: [
      "/images/products/chopping-board-flat.jpg",
      "/images/products/acacia-cutting-board.jpg",
    ],
    description:
      "An exquisite Acacia wood charcuterie and prep board, perfect for presenting cheeses, cured meats, fruits, and bread.",
    features: [
      "Wide serving area designed for charcuterie and cheese spreads",
      "Integrated handle hole for effortless carrying",
      "Pre-treated with food-safe organic mineral oil baths",
    ],
    specs: [
      { key: "Dimensions", value: "45cm L x 28cm W x 2cm H" },
      { key: "Wood Type", value: "Premium Acacia Hardwood" },
      { key: "Weight", value: "1.6 kg" },
    ],
    stock: 18,
    colors: ["Smoked Amber"],
    isBestSeller: true,
    isNewArrival: false,
  },

  // ── Serving Platters ─────────────────────────────────────────
  {
    id: "romper-acacia-tray",
    name: "Oak Luxe Serving Tray",
    slug: "romper-acacia-tray",
    category: "serving-trays",
    categoryName: "Serving Platters",
    price: 1499,
    originalPrice: 1999,
    images: [
      "/images/products/wall-shelf-1.jpg",
      "/images/products/photo-frame-1.jpg",
    ],
    description:
      "An elegant serving platter sculpted from premium Oak wood, featuring high borders and integrated handles for comfortable hosting.",
    features: [
      "Raised 1.2-inch border walls with carved integrated grip handles",
      "Water-resistant organic sealer to prevent staining from coffee/wine spills",
      "Sturdy, non-slip flat base suitable for bowls, mugs, or glasses",
      "Lightweight yet extremely durable structure",
    ],
    specs: [
      { key: "Dimensions", value: "Length 35cm, Width 25cm, Height 8cm" },
      { key: "Wood Type", value: "Oak Wood" },
      { key: "Weight", value: "1.1 kg" },
    ],
    stock: 15,
    colors: ["Natural Oak"],
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    id: "angled-handles-serving-tray",
    name: "Angled Handles Wooden Serving Platter",
    slug: "angled-handles-serving-tray",
    category: "serving-trays",
    categoryName: "Serving Platters",
    price: 999,
    originalPrice: 1399,
    images: [
      "/images/products/photo-frame-1.jpg",
      "/images/products/wall-shelf-1.jpg",
    ],
    description:
      "A contemporary wooden serving tray with ergonomic carved handle cut-outs and a smooth moisture-resistant glaze.",
    features: [
      "Ergonomic handle cut-outs for effortless grip",
      "Sturdy flat wooden base with water-resistant finish",
      "Ideal for serving drinks, appetizers, and snacks",
    ],
    specs: [
      { key: "Dimensions", value: "38cm L x 24cm W x 5cm H" },
      { key: "Wood Type", value: "Natural Hardwood" },
      { key: "Weight", value: "0.9 kg" },
    ],
    stock: 22,
    colors: ["Natural Wood"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "footed-tea-serving-tray",
    name: "Footed Wooden Tea & Breakfast Tray",
    slug: "footed-tea-serving-tray",
    category: "serving-trays",
    categoryName: "Serving Platters",
    price: 1299,
    originalPrice: 1699,
    images: [
      "/images/products/key-holder-1.jpg",
      "/images/products/wooden-temple-1.jpg",
    ],
    description:
      "A handcrafted wooden serving tray with corner feet, designed for serving morning tea, coffee, biscuits, and breakfast.",
    features: [
      "Corner footed pegs elevate the tray elegantly off table surfaces",
      "Raised perimeter border prevents mugs and saucers from slipping",
      "Water-resistant protective oil sealer for easy wipe cleaning",
    ],
    specs: [
      { key: "Dimensions", value: "30cm L x 20cm W x 8cm H" },
      { key: "Wood Type", value: "Solid Oak Wood" },
      { key: "Weight", value: "1.0 kg" },
    ],
    stock: 30,
    colors: ["Honey Oak"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "mango-wood-cake-stand",
    name: "Artisan Mango Wood Cake Stand",
    slug: "mango-wood-cake-stand",
    category: "serving-trays",
    categoryName: "Serving Platters",
    price: 1799,
    originalPrice: 2499,
    images: ["/images/products/chopping-board-flat.jpg"],
    description:
      "Make celebrations special with this rustic yet contemporary cake stand. Carved from Mango wood with a moisture-resistant food-safe glaze and a heavy pedestal stand.",
    features: [
      "Carved solid pedestal base with weighted foundation",
      "Stunning natural Mango wood grains with unique light-gold variations",
      "Ideal for displaying cakes, pastries, cheeses, or appetizers",
      "Wipes clean in seconds",
    ],
    specs: [
      { key: "Dimensions", value: '10" Diameter x 5.5" H' },
      { key: "Wood Type", value: "Premium Mango Wood" },
      { key: "Weight", value: "1.1 kg" },
    ],
    stock: 10,
    colors: ["Light Gold Mango"],
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    id: "mango-wood-salad-bowl",
    name: "Ember Serving Tray",
    slug: "mango-wood-salad-bowl",
    category: "serving-trays",
    categoryName: "Serving Platters",
    price: 1099,
    originalPrice: 1499,
    images: [
      "/images/products/wall-shelf-1.jpg",
      "/images/products/photo-frame-1.jpg",
    ],
    description:
      "A rustic yet modern serving tray made of Oak wood, featuring integrated handles and a premium matte finish.",
    features: [
      "Hand-carved from select kiln-dried Oak wood",
      "Premium moisture-resistant matte wax finish",
      "Comfortable integrated handles for secure holding",
      "Modern clean lines that highlight rich grain patterns",
    ],
    specs: [
      { key: "Dimensions", value: "Length 35cm, Width 25cm, Height 8cm" },
      { key: "Wood Type", value: "Oak Wood" },
      { key: "Weight", value: "1.0 kg" },
    ],
    stock: 20,
    colors: ["Smoked Oak"],
    isBestSeller: false,
    isNewArrival: false,
  },

  // ── Kitchen Organizers ────────────────────────────────────────
  {
    id: "traditional-roti-casserole",
    name: "Traditional Acacia Roti Casserole Box",
    slug: "traditional-roti-casserole",
    category: "kitchen-organizers",
    categoryName: "Kitchen Organizers",
    price: 1299,
    originalPrice: 1699,
    images: ["/images/products/chopping-board-v1.jpg"],
    description:
      "An elegant solution to keep your rotis, chapatis, or breads warm and fresh. Handcrafted from beautiful Acacia wood with a snug-fitting lid.",
    features: [
      "Snug wood lid helps lock in steam and moisture naturally",
      "Insulated interior space (recommend lining with a cloth napkin)",
      "Vibrant wood grains match both traditional and modern table settings",
      "Can also be used to serve tortillas, pita breads, or store snacks",
    ],
    specs: [
      { key: "Dimensions", value: '9" Diameter x 4" H' },
      { key: "Wood Type", value: "Acacia Hardwood" },
      { key: "Capacity", value: "Holds up to 15–20 flatbreads" },
    ],
    stock: 18,
    colors: ["Smoked Amber"],
    isBestSeller: true,
    isNewArrival: false,
  },
  {
    id: "acacia-cutlery-holder",
    name: "Acacia Cutlery Holder & Organizer",
    slug: "acacia-cutlery-holder",
    category: "kitchen-organizers",
    categoryName: "Kitchen Organizers",
    price: 799,
    originalPrice: 999,
    images: ["/images/products/chopping-board-v2.jpg"],
    description:
      "Keep your kitchen counters organized with this partitioned wooden holder featuring 3 spacious compartments for forks, knives, and spoons.",
    features: [
      "Three separate storage compartments for clean organization",
      "Sturdy weighted base prevents tipping even when fully loaded",
      "Compact design takes minimal space on kitchen countertops",
      "Can double as a desk organizer for pens and brushes",
    ],
    specs: [
      { key: "Dimensions", value: '8" L x 4.5" W x 6" H' },
      { key: "Wood Type", value: "Acacia Wood" },
      { key: "Compartments", value: "3 partitioned slots" },
    ],
    stock: 40,
    colors: ["Natural Grain"],
    isBestSeller: false,
    isNewArrival: true,
  },

  // ── Tableware & Sofa Accents ──────────────────────────────────
  {
    id: "acacia-sofa-arm-tray",
    name: "Premium Acacia Sofa Arm Tray",
    slug: "acacia-sofa-arm-tray",
    category: "tableware-living",
    categoryName: "Tableware & Sofa Accents",
    price: 899,
    originalPrice: 1199,
    images: ["/images/products/chopping-board-h1.jpg"],
    description:
      "Flexible slatted wooden blocks joined by a high-grip felt backing that wraps snugly over any sofa armrest, providing a stable surface for your coffee or remote.",
    features: [
      "Flexible slatted design conforms easily to various armrest widths",
      "Non-slip protective fabric backing prevents slipping and protects sofa fabrics",
      "Spill-resistant protective coating makes cleanup extremely simple",
      "Slim profile is easy to roll up and store when not in use",
    ],
    specs: [
      { key: "Dimensions", value: '16" L x 10" W x 0.35" H' },
      { key: "Wood Type", value: "Acacia Wood" },
      { key: "Backing", value: "High-grip protective polyester felt" },
    ],
    stock: 30,
    colors: ["Charcoal Ash", "Warm Chestnut"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "acacia-coaster-set",
    name: "Minimalist Acacia Coasters (Set of 6)",
    slug: "acacia-coaster-set",
    category: "tableware-living",
    categoryName: "Tableware & Sofa Accents",
    price: 499,
    originalPrice: 699,
    images: ["/images/products/chopping-board-h1.jpg"],
    description:
      "Six round Acacia wood coasters with a matching wood storage stand. Each coaster displays a beautiful cross-section of wood timber grain.",
    features: [
      "Includes 6 round coasters and 1 compact wooden organizer stand",
      "Raised perimeter lip catches condensation droplets from cold glasses",
      "Soft padded bottom dots prevent scratching on glass or wood surfaces",
      "Heat-resistant to protect surfaces from hot coffee mugs",
    ],
    specs: [
      {
        key: "Dimensions",
        value: 'Coaster: 3.8" Diameter | Stand: 4.5" L x 4.5" W',
      },
      { key: "Wood Type", value: "Acacia Wood" },
      { key: "Pack Size", value: "6 Coasters + 1 Stand" },
    ],
    stock: 60,
    colors: ["Chestnut Honey"],
    isBestSeller: false,
    isNewArrival: false,
  },

  // ── Wall Decor ────────────────────────────────────────────────
  {
    id: "key-holder",
    name: "Artisan Wooden Key Holder",
    slug: "key-holder",
    category: "wall-decor",
    categoryName: "Wall Decor",
    price: 699,
    originalPrice: 999,
    images: [
      "/images/products/key-holder-1.jpg",
      "/images/products/key-holder-2.jpg",
      "/images/products/key-holder-3.jpg",
    ],
    description:
      "A hand-crafted wooden key holder featuring high-quality metal hooks and a top shelf for small decor items, bringing warmth to your entryway.",
    features: [
      "Sleek and minimalist design suitable for any home entryway",
      "Includes 5 sturdy antique bronze key hooks",
      "Built-in display shelf for mail, plants, or small ornaments",
      "Easy wall mounting setup with all hardware included",
    ],
    specs: [
      { key: "Dimensions", value: "30cm L x 12cm W x 10cm H" },
      { key: "Material", value: "Solid Wood" },
      { key: "Finish", value: "Natural wax finish" },
    ],
    stock: 15,
    colors: ["Honey Brown"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "wooden-temple",
    name: "Hand-carved Wooden Temple",
    slug: "wooden-temple",
    category: "wall-decor",
    categoryName: "Wall Decor",
    price: 2499,
    originalPrice: 3499,
    images: [
      "/images/products/wooden-temple-1.jpg",
      "/images/products/wooden-temple-2.jpg",
      "/images/products/wooden-temple-3.jpg",
    ],
    description:
      "An architectural masterpiece for your home sanctuary. Hand-carved from solid wood with intricate details, providing a sacred and beautiful space for prayers.",
    features: [
      "Intricate hand-carved details by master artisans",
      "Features a pull-out tray for incense or light offerings",
      "Durable wall-mounting capability or tabletop placement",
      "Finished with natural non-toxic lacquer",
    ],
    specs: [
      { key: "Dimensions", value: "45cm H x 30cm W x 20cm D" },
      { key: "Material", value: "Premium Hardwood" },
      { key: "Finish", value: "Teak brown polish" },
    ],
    stock: 8,
    colors: ["Classic Teak"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "wall-shelf",
    name: "Floating Wooden Wall Shelf",
    slug: "wall-shelf",
    category: "wall-decor",
    categoryName: "Wall Decor",
    price: 899,
    originalPrice: 1299,
    images: [
      "/images/products/wall-shelf-1.jpg",
      "/images/products/wall-shelf-2.jpg",
      "/images/products/wall-shelf-3.jpg",
    ],
    description:
      "Elevate your room design with this floating wall shelf. Perfect for organizing books, displaying succulent planters, or styling decorative items.",
    features: [
      "Sturdy build with invisible metal wall brackets",
      "Rich wood grain lines that showcase natural timber beauty",
      "Perfect for bedrooms, living rooms, and kitchen spices",
      "Eco-friendly timber sourcing and non-toxic clear finish",
    ],
    specs: [
      { key: "Dimensions", value: "60cm L x 15cm W x 4cm H" },
      { key: "Material", value: "Premium Pine Wood" },
      { key: "Capacity", value: "Holds up to 10 kg" },
    ],
    stock: 22,
    colors: ["Natural Pine"],
    isBestSeller: false,
    isNewArrival: true,
  },
  {
    id: "photo-frame",
    name: "Premium Wooden Photo Frame",
    slug: "photo-frame",
    category: "wall-decor",
    categoryName: "Wall Decor",
    price: 499,
    originalPrice: 799,
    images: [
      "/images/products/photo-frame-1.jpg",
      "/images/products/photo-frame-2.jpg",
      "/images/products/photo-frame-3.jpg",
    ],
    description:
      "Frame your memories in natural warmth. Crafted from premium organic wood with a durable easel stand and wall mounting clips.",
    features: [
      "Suitable for both wall hanging and tabletop displays",
      "Equipped with real high-transparency protective glass",
      "Easy-open back panel for quick photo changes",
      "Clean, timeless layout matches any decor style",
    ],
    specs: [
      { key: "Dimensions", value: 'Fits 8" x 10" photographs' },
      { key: "Material", value: "Natural Wood" },
      { key: "Finish", value: "Oak wood polish" },
    ],
    stock: 45,
    colors: ["Natural Oak"],
    isBestSeller: false,
    isNewArrival: true,
  },
];

export const getProductById = (id) => products.find((p) => p.id === id);
export const getProductsByCategory = (category) =>
  products.filter((p) => p.category === category);
export const getFeaturedProducts = () => products.filter((p) => p.isBestSeller);
export const getNewArrivals = () => products.filter((p) => p.isNewArrival);
